---
- name: Update all nodes
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Update and upgrade apt packages on Ubuntu/Debian
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update and upgrade yum packages on CentOS/Red Hat
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

